language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-stable

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  global:
    - PATH="$HOME/texlive/bin/x86_64-linux:$PWD/build:$PATH"

install:
  - git clone https://github.com/pillar-markup/pillar.git -b dev-7
  - ./pillar/scripts/ci/install-texlive
  - ./_support/latex/ensure-deps.sh
  - ./pillar/scripts/build.sh

script:
  - pillar build pdf

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv _result/pdf/withstylebook.pdf WithStyleBook-wip.pdf
  - bash upload.sh WithStyleBook-wip.pdf

branches:
  except:
    - /^(?i:continuous)$/
